// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: companion.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCompanionCloseConversation = "/companion.v1.Companion/CloseConversation"
const OperationCompanionCreateConversation = "/companion.v1.Companion/CreateConversation"
const OperationCompanionDeleteData = "/companion.v1.Companion/DeleteData"
const OperationCompanionExportData = "/companion.v1.Companion/ExportData"
const OperationCompanionGetConversation = "/companion.v1.Companion/GetConversation"
const OperationCompanionListConversations = "/companion.v1.Companion/ListConversations"
const OperationCompanionSendAudioMessage = "/companion.v1.Companion/SendAudioMessage"
const OperationCompanionSendMessage = "/companion.v1.Companion/SendMessage"
const OperationCompanionSubmitMemoryFeedback = "/companion.v1.Companion/SubmitMemoryFeedback"

type CompanionHTTPServer interface {
	CloseConversation(context.Context, *CloseConversationRequest) (*ConversationReply, error)
	CreateConversation(context.Context, *CreateConversationRequest) (*ConversationReply, error)
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataReply, error)
	ExportData(context.Context, *ExportDataRequest) (*ExportDataReply, error)
	GetConversation(context.Context, *GetConversationRequest) (*ConversationReply, error)
	ListConversations(context.Context, *ListConversationsRequest) (*ConversationListReply, error)
	SendAudioMessage(context.Context, *SendAudioMessageRequest) (*SendAudioMessageReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	SubmitMemoryFeedback(context.Context, *MemoryFeedbackRequest) (*MemoryFeedbackReply, error)
}

func RegisterCompanionHTTPServer(s *http.Server, srv CompanionHTTPServer) {
	r := s.Route("/")
	r.POST("/companion/v1/conversations", _Companion_CreateConversation0_HTTP_Handler(srv))
	r.GET("/companion/v1/conversations/{conversation_id}", _Companion_GetConversation0_HTTP_Handler(srv))
	r.GET("/companion/v1/conversations", _Companion_ListConversations0_HTTP_Handler(srv))
	r.POST("/companion/v1/conversations/{conversation_id}/messages", _Companion_SendMessage0_HTTP_Handler(srv))
	r.POST("/companion/v1/conversations/{conversation_id}/audio-messages", _Companion_SendAudioMessage0_HTTP_Handler(srv))
	r.POST("/companion/v1/conversations/{conversation_id}/memory-feedback", _Companion_SubmitMemoryFeedback0_HTTP_Handler(srv))
	r.POST("/companion/v1/conversations/{conversation_id}/close", _Companion_CloseConversation0_HTTP_Handler(srv))
	r.POST("/companion/v1/data/export", _Companion_ExportData0_HTTP_Handler(srv))
	r.POST("/companion/v1/data/delete", _Companion_DeleteData0_HTTP_Handler(srv))
}

func _Companion_CreateConversation0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConversationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionCreateConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConversation(ctx, req.(*CreateConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetConversation0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConversationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConversation(ctx, req.(*GetConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListConversations0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConversationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListConversations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConversations(ctx, req.(*ListConversationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationListReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SendMessage0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SendAudioMessage0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendAudioMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSendAudioMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendAudioMessage(ctx, req.(*SendAudioMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendAudioMessageReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SubmitMemoryFeedback0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MemoryFeedbackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSubmitMemoryFeedback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitMemoryFeedback(ctx, req.(*MemoryFeedbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemoryFeedbackReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_CloseConversation0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CloseConversationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionCloseConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CloseConversation(ctx, req.(*CloseConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ExportData0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportDataRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionExportData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportData(ctx, req.(*ExportDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportDataReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_DeleteData0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDataRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionDeleteData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteData(ctx, req.(*DeleteDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDataReply)
		return ctx.Result(200, reply)
	}
}

type CompanionHTTPClient interface {
	CloseConversation(ctx context.Context, req *CloseConversationRequest, opts ...http.CallOption) (rsp *ConversationReply, err error)
	CreateConversation(ctx context.Context, req *CreateConversationRequest, opts ...http.CallOption) (rsp *ConversationReply, err error)
	DeleteData(ctx context.Context, req *DeleteDataRequest, opts ...http.CallOption) (rsp *DeleteDataReply, err error)
	ExportData(ctx context.Context, req *ExportDataRequest, opts ...http.CallOption) (rsp *ExportDataReply, err error)
	GetConversation(ctx context.Context, req *GetConversationRequest, opts ...http.CallOption) (rsp *ConversationReply, err error)
	ListConversations(ctx context.Context, req *ListConversationsRequest, opts ...http.CallOption) (rsp *ConversationListReply, err error)
	SendAudioMessage(ctx context.Context, req *SendAudioMessageRequest, opts ...http.CallOption) (rsp *SendAudioMessageReply, err error)
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
	SubmitMemoryFeedback(ctx context.Context, req *MemoryFeedbackRequest, opts ...http.CallOption) (rsp *MemoryFeedbackReply, err error)
}

type CompanionHTTPClientImpl struct {
	cc *http.Client
}

func NewCompanionHTTPClient(client *http.Client) CompanionHTTPClient {
	return &CompanionHTTPClientImpl{client}
}

func (c *CompanionHTTPClientImpl) CloseConversation(ctx context.Context, in *CloseConversationRequest, opts ...http.CallOption) (*ConversationReply, error) {
	var out ConversationReply
	pattern := "/companion/v1/conversations/{conversation_id}/close"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionCloseConversation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...http.CallOption) (*ConversationReply, error) {
	var out ConversationReply
	pattern := "/companion/v1/conversations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionCreateConversation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...http.CallOption) (*DeleteDataReply, error) {
	var out DeleteDataReply
	pattern := "/companion/v1/data/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionDeleteData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ExportData(ctx context.Context, in *ExportDataRequest, opts ...http.CallOption) (*ExportDataReply, error) {
	var out ExportDataReply
	pattern := "/companion/v1/data/export"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionExportData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...http.CallOption) (*ConversationReply, error) {
	var out ConversationReply
	pattern := "/companion/v1/conversations/{conversation_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetConversation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...http.CallOption) (*ConversationListReply, error) {
	var out ConversationListReply
	pattern := "/companion/v1/conversations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListConversations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SendAudioMessage(ctx context.Context, in *SendAudioMessageRequest, opts ...http.CallOption) (*SendAudioMessageReply, error) {
	var out SendAudioMessageReply
	pattern := "/companion/v1/conversations/{conversation_id}/audio-messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSendAudioMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/companion/v1/conversations/{conversation_id}/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SubmitMemoryFeedback(ctx context.Context, in *MemoryFeedbackRequest, opts ...http.CallOption) (*MemoryFeedbackReply, error) {
	var out MemoryFeedbackReply
	pattern := "/companion/v1/conversations/{conversation_id}/memory-feedback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSubmitMemoryFeedback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
