// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: companion.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Assets        []*MessageAsset        `protobuf:"bytes,5,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_companion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConversationMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConversationMessage) GetAssets() []*MessageAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type MessageAsset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageAssetId string                 `protobuf:"bytes,1,opt,name=message_asset_id,json=messageAssetId,proto3" json:"message_asset_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	MediaType      string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	ContentType    string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename       string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	Url            string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageAsset) Reset() {
	*x = MessageAsset{}
	mi := &file_companion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAsset) ProtoMessage() {}

func (x *MessageAsset) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAsset.ProtoReflect.Descriptor instead.
func (*MessageAsset) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{1}
}

func (x *MessageAsset) GetMessageAssetId() string {
	if x != nil {
		return x.MessageAssetId
	}
	return ""
}

func (x *MessageAsset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *MessageAsset) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MessageAsset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MessageAsset) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MessageAsset) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageAsset) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type GetTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelineRequest) Reset() {
	*x = GetTimelineRequest{}
	mi := &file_companion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineRequest) ProtoMessage() {}

func (x *GetTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetTimelineRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimelineRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TimelineReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConversationMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineReply) Reset() {
	*x = TimelineReply{}
	mi := &file_companion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineReply) ProtoMessage() {}

func (x *TimelineReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineReply.ProtoReflect.Descriptor instead.
func (*TimelineReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{3}
}

func (x *TimelineReply) GetMessages() []*ConversationMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_companion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserMessage      *ConversationMessage   `protobuf:"bytes,1,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AssistantMessage *ConversationMessage   `protobuf:"bytes,2,opt,name=assistant_message,json=assistantMessage,proto3" json:"assistant_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_companion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageReply) GetUserMessage() *ConversationMessage {
	if x != nil {
		return x.UserMessage
	}
	return nil
}

func (x *SendMessageReply) GetAssistantMessage() *ConversationMessage {
	if x != nil {
		return x.AssistantMessage
	}
	return nil
}

type SendAudioMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Voice         string                 `protobuf:"bytes,5,opt,name=voice,proto3" json:"voice,omitempty"`
	Synthesize    bool                   `protobuf:"varint,6,opt,name=synthesize,proto3" json:"synthesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAudioMessageRequest) Reset() {
	*x = SendAudioMessageRequest{}
	mi := &file_companion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAudioMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAudioMessageRequest) ProtoMessage() {}

func (x *SendAudioMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAudioMessageRequest.ProtoReflect.Descriptor instead.
func (*SendAudioMessageRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{6}
}

func (x *SendAudioMessageRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *SendAudioMessageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SendAudioMessageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SendAudioMessageRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SendAudioMessageRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SendAudioMessageRequest) GetSynthesize() bool {
	if x != nil {
		return x.Synthesize
	}
	return false
}

type SendAudioMessageReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          *SendMessageReply      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	AudioData        []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	AudioContentType string                 `protobuf:"bytes,3,opt,name=audio_content_type,json=audioContentType,proto3" json:"audio_content_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendAudioMessageReply) Reset() {
	*x = SendAudioMessageReply{}
	mi := &file_companion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAudioMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAudioMessageReply) ProtoMessage() {}

func (x *SendAudioMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAudioMessageReply.ProtoReflect.Descriptor instead.
func (*SendAudioMessageReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{7}
}

func (x *SendAudioMessageReply) GetMessage() *SendMessageReply {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendAudioMessageReply) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *SendAudioMessageReply) GetAudioContentType() string {
	if x != nil {
		return x.AudioContentType
	}
	return ""
}

type SendMediaMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Caption       string                 `protobuf:"bytes,5,opt,name=caption,proto3" json:"caption,omitempty"`
	Synthesize    bool                   `protobuf:"varint,6,opt,name=synthesize,proto3" json:"synthesize,omitempty"`
	Voice         string                 `protobuf:"bytes,7,opt,name=voice,proto3" json:"voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMediaMessageRequest) Reset() {
	*x = SendMediaMessageRequest{}
	mi := &file_companion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaMessageRequest) ProtoMessage() {}

func (x *SendMediaMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMediaMessageRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{8}
}

func (x *SendMediaMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendMediaMessageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SendMediaMessageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SendMediaMessageRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *SendMediaMessageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *SendMediaMessageRequest) GetSynthesize() bool {
	if x != nil {
		return x.Synthesize
	}
	return false
}

func (x *SendMediaMessageRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

type SendMediaMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *SendMessageReply      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMediaMessageReply) Reset() {
	*x = SendMediaMessageReply{}
	mi := &file_companion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaMessageReply) ProtoMessage() {}

func (x *SendMediaMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaMessageReply.ProtoReflect.Descriptor instead.
func (*SendMediaMessageReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{9}
}

func (x *SendMediaMessageReply) GetMessage() *SendMessageReply {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageChunk) Reset() {
	*x = MessageChunk{}
	mi := &file_companion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChunk) ProtoMessage() {}

func (x *MessageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChunk.ProtoReflect.Descriptor instead.
func (*MessageChunk) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{10}
}

func (x *MessageChunk) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *MessageChunk) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *MessageChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type MemoryFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryFeedbackRequest) Reset() {
	*x = MemoryFeedbackRequest{}
	mi := &file_companion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryFeedbackRequest) ProtoMessage() {}

func (x *MemoryFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryFeedbackRequest.ProtoReflect.Descriptor instead.
func (*MemoryFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{11}
}

func (x *MemoryFeedbackRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MemoryFeedbackRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MemoryFeedbackRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MemoryFeedbackRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MemoryFeedbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryFeedbackReply) Reset() {
	*x = MemoryFeedbackReply{}
	mi := &file_companion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryFeedbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryFeedbackReply) ProtoMessage() {}

func (x *MemoryFeedbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryFeedbackReply.ProtoReflect.Descriptor instead.
func (*MemoryFeedbackReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{12}
}

func (x *MemoryFeedbackReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_companion_proto protoreflect.FileDescriptor

const file_companion_proto_rawDesc = "" +
	"\n" +
	"\x0fcompanion.proto\x12\fcompanion.v1\x1a\x1cgoogle/api/annotations.proto\"\xb5\x01\n" +
	"\x13ConversationMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x122\n" +
	"\x06assets\x18\x05 \x03(\v2\x1a.companion.v1.MessageAssetR\x06assets\"\xe2\x01\n" +
	"\fMessageAsset\x12(\n" +
	"\x10message_asset_id\x18\x01 \x01(\tR\x0emessageAssetId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\"*\n" +
	"\x12GetTimelineRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"N\n" +
	"\rTimelineReply\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.companion.v1.ConversationMessageR\bmessages\".\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xa8\x01\n" +
	"\x10SendMessageReply\x12D\n" +
	"\fuser_message\x18\x01 \x01(\v2!.companion.v1.ConversationMessageR\vuserMessage\x12N\n" +
	"\x11assistant_message\x18\x02 \x01(\v2!.companion.v1.ConversationMessageR\x10assistantMessage\"\xc9\x01\n" +
	"\x17SendAudioMessageRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x14\n" +
	"\x05voice\x18\x05 \x01(\tR\x05voice\x12\x1e\n" +
	"\n" +
	"synthesize\x18\x06 \x01(\bR\n" +
	"synthesize\"\x9e\x01\n" +
	"\x15SendAudioMessageReply\x128\n" +
	"\amessage\x18\x01 \x01(\v2\x1e.companion.v1.SendMessageReplyR\amessage\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12,\n" +
	"\x12audio_content_type\x18\x03 \x01(\tR\x10audioContentType\"\xdb\x01\n" +
	"\x17SendMediaMessageRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x18\n" +
	"\acaption\x18\x05 \x01(\tR\acaption\x12\x1e\n" +
	"\n" +
	"synthesize\x18\x06 \x01(\bR\n" +
	"synthesize\x12\x14\n" +
	"\x05voice\x18\a \x01(\tR\x05voice\"Q\n" +
	"\x15SendMediaMessageReply\x128\n" +
	"\amessage\x18\x01 \x01(\v2\x1e.companion.v1.SendMessageReplyR\amessage\"|\n" +
	"\fMessageChunk\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"|\n" +
	"\x15MemoryFeedbackRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"1\n" +
	"\x13MemoryFeedbackReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xb7\x05\n" +
	"\tCompanion\x12l\n" +
	"\vGetTimeline\x12 .companion.v1.GetTimelineRequest\x1a\x1b.companion.v1.TimelineReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/companion/v1/timeline\x12r\n" +
	"\vSendMessage\x12 .companion.v1.SendMessageRequest\x1a\x1e.companion.v1.SendMessageReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/companion/v1/messages\x12S\n" +
	"\x11SendMessageStream\x12 .companion.v1.SendMessageRequest\x1a\x1a.companion.v1.MessageChunk0\x01\x12\x87\x01\n" +
	"\x10SendAudioMessage\x12%.companion.v1.SendAudioMessageRequest\x1a#.companion.v1.SendAudioMessageReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/companion/v1/audio-messages\x12^\n" +
	"\x10SendMediaMessage\x12%.companion.v1.SendMediaMessageRequest\x1a#.companion.v1.SendMediaMessageReply\x12\x88\x01\n" +
	"\x14SubmitMemoryFeedback\x12#.companion.v1.MemoryFeedbackRequest\x1a!.companion.v1.MemoryFeedbackReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/companion/v1/memory-feedbackB'Z%companion-service/api/companion/v1;v1b\x06proto3"

var (
	file_companion_proto_rawDescOnce sync.Once
	file_companion_proto_rawDescData []byte
)

func file_companion_proto_rawDescGZIP() []byte {
	file_companion_proto_rawDescOnce.Do(func() {
		file_companion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_companion_proto_rawDesc), len(file_companion_proto_rawDesc)))
	})
	return file_companion_proto_rawDescData
}

var file_companion_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_companion_proto_goTypes = []any{
	(*ConversationMessage)(nil),     // 0: companion.v1.ConversationMessage
	(*MessageAsset)(nil),            // 1: companion.v1.MessageAsset
	(*GetTimelineRequest)(nil),      // 2: companion.v1.GetTimelineRequest
	(*TimelineReply)(nil),           // 3: companion.v1.TimelineReply
	(*SendMessageRequest)(nil),      // 4: companion.v1.SendMessageRequest
	(*SendMessageReply)(nil),        // 5: companion.v1.SendMessageReply
	(*SendAudioMessageRequest)(nil), // 6: companion.v1.SendAudioMessageRequest
	(*SendAudioMessageReply)(nil),   // 7: companion.v1.SendAudioMessageReply
	(*SendMediaMessageRequest)(nil), // 8: companion.v1.SendMediaMessageRequest
	(*SendMediaMessageReply)(nil),   // 9: companion.v1.SendMediaMessageReply
	(*MessageChunk)(nil),            // 10: companion.v1.MessageChunk
	(*MemoryFeedbackRequest)(nil),   // 11: companion.v1.MemoryFeedbackRequest
	(*MemoryFeedbackReply)(nil),     // 12: companion.v1.MemoryFeedbackReply
}
var file_companion_proto_depIdxs = []int32{
	1,  // 0: companion.v1.ConversationMessage.assets:type_name -> companion.v1.MessageAsset
	0,  // 1: companion.v1.TimelineReply.messages:type_name -> companion.v1.ConversationMessage
	0,  // 2: companion.v1.SendMessageReply.user_message:type_name -> companion.v1.ConversationMessage
	0,  // 3: companion.v1.SendMessageReply.assistant_message:type_name -> companion.v1.ConversationMessage
	5,  // 4: companion.v1.SendAudioMessageReply.message:type_name -> companion.v1.SendMessageReply
	5,  // 5: companion.v1.SendMediaMessageReply.message:type_name -> companion.v1.SendMessageReply
	2,  // 6: companion.v1.Companion.GetTimeline:input_type -> companion.v1.GetTimelineRequest
	4,  // 7: companion.v1.Companion.SendMessage:input_type -> companion.v1.SendMessageRequest
	4,  // 8: companion.v1.Companion.SendMessageStream:input_type -> companion.v1.SendMessageRequest
	6,  // 9: companion.v1.Companion.SendAudioMessage:input_type -> companion.v1.SendAudioMessageRequest
	8,  // 10: companion.v1.Companion.SendMediaMessage:input_type -> companion.v1.SendMediaMessageRequest
	11, // 11: companion.v1.Companion.SubmitMemoryFeedback:input_type -> companion.v1.MemoryFeedbackRequest
	3,  // 12: companion.v1.Companion.GetTimeline:output_type -> companion.v1.TimelineReply
	5,  // 13: companion.v1.Companion.SendMessage:output_type -> companion.v1.SendMessageReply
	10, // 14: companion.v1.Companion.SendMessageStream:output_type -> companion.v1.MessageChunk
	7,  // 15: companion.v1.Companion.SendAudioMessage:output_type -> companion.v1.SendAudioMessageReply
	9,  // 16: companion.v1.Companion.SendMediaMessage:output_type -> companion.v1.SendMediaMessageReply
	12, // 17: companion.v1.Companion.SubmitMemoryFeedback:output_type -> companion.v1.MemoryFeedbackReply
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_companion_proto_init() }
func file_companion_proto_init() {
	if File_companion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_companion_proto_rawDesc), len(file_companion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_companion_proto_goTypes,
		DependencyIndexes: file_companion_proto_depIdxs,
		MessageInfos:      file_companion_proto_msgTypes,
	}.Build()
	File_companion_proto = out.File
	file_companion_proto_goTypes = nil
	file_companion_proto_depIdxs = nil
}
