// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: companion.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Companion_GetTimeline_FullMethodName          = "/companion.v1.Companion/GetTimeline"
	Companion_SendMessage_FullMethodName          = "/companion.v1.Companion/SendMessage"
	Companion_SendMessageStream_FullMethodName    = "/companion.v1.Companion/SendMessageStream"
	Companion_SendAudioMessage_FullMethodName     = "/companion.v1.Companion/SendAudioMessage"
	Companion_SendMediaMessage_FullMethodName     = "/companion.v1.Companion/SendMediaMessage"
	Companion_SubmitMemoryFeedback_FullMethodName = "/companion.v1.Companion/SubmitMemoryFeedback"
)

// CompanionClient is the client API for Companion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompanionClient interface {
	GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*TimelineReply, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	SendMessageStream(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageChunk], error)
	SendAudioMessage(ctx context.Context, in *SendAudioMessageRequest, opts ...grpc.CallOption) (*SendAudioMessageReply, error)
	SendMediaMessage(ctx context.Context, in *SendMediaMessageRequest, opts ...grpc.CallOption) (*SendMediaMessageReply, error)
	SubmitMemoryFeedback(ctx context.Context, in *MemoryFeedbackRequest, opts ...grpc.CallOption) (*MemoryFeedbackReply, error)
}

type companionClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanionClient(cc grpc.ClientConnInterface) CompanionClient {
	return &companionClient{cc}
}

func (c *companionClient) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*TimelineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineReply)
	err := c.cc.Invoke(ctx, Companion_GetTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companionClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, Companion_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companionClient) SendMessageStream(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Companion_ServiceDesc.Streams[0], Companion_SendMessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, MessageChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Companion_SendMessageStreamClient = grpc.ServerStreamingClient[MessageChunk]

func (c *companionClient) SendAudioMessage(ctx context.Context, in *SendAudioMessageRequest, opts ...grpc.CallOption) (*SendAudioMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAudioMessageReply)
	err := c.cc.Invoke(ctx, Companion_SendAudioMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companionClient) SendMediaMessage(ctx context.Context, in *SendMediaMessageRequest, opts ...grpc.CallOption) (*SendMediaMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMediaMessageReply)
	err := c.cc.Invoke(ctx, Companion_SendMediaMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companionClient) SubmitMemoryFeedback(ctx context.Context, in *MemoryFeedbackRequest, opts ...grpc.CallOption) (*MemoryFeedbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryFeedbackReply)
	err := c.cc.Invoke(ctx, Companion_SubmitMemoryFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanionServer is the server API for Companion service.
// All implementations must embed UnimplementedCompanionServer
// for forward compatibility.
type CompanionServer interface {
	GetTimeline(context.Context, *GetTimelineRequest) (*TimelineReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	SendMessageStream(*SendMessageRequest, grpc.ServerStreamingServer[MessageChunk]) error
	SendAudioMessage(context.Context, *SendAudioMessageRequest) (*SendAudioMessageReply, error)
	SendMediaMessage(context.Context, *SendMediaMessageRequest) (*SendMediaMessageReply, error)
	SubmitMemoryFeedback(context.Context, *MemoryFeedbackRequest) (*MemoryFeedbackReply, error)
	mustEmbedUnimplementedCompanionServer()
}

// UnimplementedCompanionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompanionServer struct{}

func (UnimplementedCompanionServer) GetTimeline(context.Context, *GetTimelineRequest) (*TimelineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedCompanionServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedCompanionServer) SendMessageStream(*SendMessageRequest, grpc.ServerStreamingServer[MessageChunk]) error {
	return status.Error(codes.Unimplemented, "method SendMessageStream not implemented")
}
func (UnimplementedCompanionServer) SendAudioMessage(context.Context, *SendAudioMessageRequest) (*SendAudioMessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAudioMessage not implemented")
}
func (UnimplementedCompanionServer) SendMediaMessage(context.Context, *SendMediaMessageRequest) (*SendMediaMessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMediaMessage not implemented")
}
func (UnimplementedCompanionServer) SubmitMemoryFeedback(context.Context, *MemoryFeedbackRequest) (*MemoryFeedbackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMemoryFeedback not implemented")
}
func (UnimplementedCompanionServer) mustEmbedUnimplementedCompanionServer() {}
func (UnimplementedCompanionServer) testEmbeddedByValue()                   {}

// UnsafeCompanionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanionServer will
// result in compilation errors.
type UnsafeCompanionServer interface {
	mustEmbedUnimplementedCompanionServer()
}

func RegisterCompanionServer(s grpc.ServiceRegistrar, srv CompanionServer) {
	// If the following call panics, it indicates UnimplementedCompanionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Companion_ServiceDesc, srv)
}

func _Companion_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Companion_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServer).GetTimeline(ctx, req.(*GetTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Companion_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Companion_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Companion_SendMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompanionServer).SendMessageStream(m, &grpc.GenericServerStream[SendMessageRequest, MessageChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Companion_SendMessageStreamServer = grpc.ServerStreamingServer[MessageChunk]

func _Companion_SendAudioMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAudioMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServer).SendAudioMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Companion_SendAudioMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServer).SendAudioMessage(ctx, req.(*SendAudioMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Companion_SendMediaMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServer).SendMediaMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Companion_SendMediaMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServer).SendMediaMessage(ctx, req.(*SendMediaMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Companion_SubmitMemoryFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServer).SubmitMemoryFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Companion_SubmitMemoryFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServer).SubmitMemoryFeedback(ctx, req.(*MemoryFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Companion_ServiceDesc is the grpc.ServiceDesc for Companion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Companion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "companion.v1.Companion",
	HandlerType: (*CompanionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeline",
			Handler:    _Companion_GetTimeline_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Companion_SendMessage_Handler,
		},
		{
			MethodName: "SendAudioMessage",
			Handler:    _Companion_SendAudioMessage_Handler,
		},
		{
			MethodName: "SendMediaMessage",
			Handler:    _Companion_SendMediaMessage_Handler,
		},
		{
			MethodName: "SubmitMemoryFeedback",
			Handler:    _Companion_SubmitMemoryFeedback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessageStream",
			Handler:       _Companion_SendMessageStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "companion.proto",
}
