// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: companion.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Conversation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Conversation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Conversation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConversationMultiError, or
// nil if none found.
func (m *Conversation) ValidateAll() error {
	return m.validate(true)
}

func (m *Conversation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConversationId

	// no validation rules for UserId

	// no validation rules for CompanionId

	// no validation rules for Status

	// no validation rules for Summary

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConversationValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConversationValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConversationValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return ConversationMultiError(errors)
	}

	return nil
}

// ConversationMultiError is an error wrapping multiple validation errors
// returned by Conversation.ValidateAll() if the designated constraints aren't met.
type ConversationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationMultiError) AllErrors() []error { return m }

// ConversationValidationError is the validation error returned by
// Conversation.Validate if the designated constraints aren't met.
type ConversationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationValidationError) ErrorName() string { return "ConversationValidationError" }

// Error satisfies the builtin error interface
func (e ConversationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationValidationError{}

// Validate checks the field values on ConversationMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConversationMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationMessageMultiError, or nil if none found.
func (m *ConversationMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageId

	// no validation rules for Role

	// no validation rules for Content

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return ConversationMessageMultiError(errors)
	}

	return nil
}

// ConversationMessageMultiError is an error wrapping multiple validation
// errors returned by ConversationMessage.ValidateAll() if the designated
// constraints aren't met.
type ConversationMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationMessageMultiError) AllErrors() []error { return m }

// ConversationMessageValidationError is the validation error returned by
// ConversationMessage.Validate if the designated constraints aren't met.
type ConversationMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationMessageValidationError) ErrorName() string {
	return "ConversationMessageValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationMessageValidationError{}

// Validate checks the field values on CreateConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateConversationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateConversationRequestMultiError, or nil if none found.
func (m *CreateConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CompanionId

	if len(errors) > 0 {
		return CreateConversationRequestMultiError(errors)
	}

	return nil
}

// CreateConversationRequestMultiError is an error wrapping multiple validation
// errors returned by CreateConversationRequest.ValidateAll() if the
// designated constraints aren't met.
type CreateConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateConversationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateConversationRequestMultiError) AllErrors() []error { return m }

// CreateConversationRequestValidationError is the validation error returned by
// CreateConversationRequest.Validate if the designated constraints aren't met.
type CreateConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateConversationRequestValidationError) ErrorName() string {
	return "CreateConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateConversationRequestValidationError{}

// Validate checks the field values on GetConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetConversationRequestMultiError, or nil if none found.
func (m *GetConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConversationId

	if len(errors) > 0 {
		return GetConversationRequestMultiError(errors)
	}

	return nil
}

// GetConversationRequestMultiError is an error wrapping multiple validation
// errors returned by GetConversationRequest.ValidateAll() if the designated
// constraints aren't met.
type GetConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetConversationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetConversationRequestMultiError) AllErrors() []error { return m }

// GetConversationRequestValidationError is the validation error returned by
// GetConversationRequest.Validate if the designated constraints aren't met.
type GetConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetConversationRequestValidationError) ErrorName() string {
	return "GetConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetConversationRequestValidationError{}

// Validate checks the field values on SendMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageRequestMultiError, or nil if none found.
func (m *SendMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConversationId

	// no validation rules for Content

	if len(errors) > 0 {
		return SendMessageRequestMultiError(errors)
	}

	return nil
}

// SendMessageRequestMultiError is an error wrapping multiple validation errors
// returned by SendMessageRequest.ValidateAll() if the designated constraints
// aren't met.
type SendMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageRequestMultiError) AllErrors() []error { return m }

// SendMessageRequestValidationError is the validation error returned by
// SendMessageRequest.Validate if the designated constraints aren't met.
type SendMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageRequestValidationError) ErrorName() string {
	return "SendMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageRequestValidationError{}

// Validate checks the field values on ConversationReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConversationReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationReplyMultiError, or nil if none found.
func (m *ConversationReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConversation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConversationReplyValidationError{
					field:  "Conversation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConversationReplyValidationError{
					field:  "Conversation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConversation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConversationReplyValidationError{
				field:  "Conversation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ConversationReplyMultiError(errors)
	}

	return nil
}

// ConversationReplyMultiError is an error wrapping multiple validation errors
// returned by ConversationReply.ValidateAll() if the designated constraints
// aren't met.
type ConversationReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationReplyMultiError) AllErrors() []error { return m }

// ConversationReplyValidationError is the validation error returned by
// ConversationReply.Validate if the designated constraints aren't met.
type ConversationReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationReplyValidationError) ErrorName() string {
	return "ConversationReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationReplyValidationError{}

// Validate checks the field values on SendMessageReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageReplyMultiError, or nil if none found.
func (m *SendMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUserMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "UserMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "UserMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendMessageReplyValidationError{
				field:  "UserMessage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAssistantMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "AssistantMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "AssistantMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAssistantMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendMessageReplyValidationError{
				field:  "AssistantMessage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SendMessageReplyMultiError(errors)
	}

	return nil
}

// SendMessageReplyMultiError is an error wrapping multiple validation errors
// returned by SendMessageReply.ValidateAll() if the designated constraints
// aren't met.
type SendMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageReplyMultiError) AllErrors() []error { return m }

// SendMessageReplyValidationError is the validation error returned by
// SendMessageReply.Validate if the designated constraints aren't met.
type SendMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageReplyValidationError) ErrorName() string { return "SendMessageReplyValidationError" }

// Error satisfies the builtin error interface
func (e SendMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageReplyValidationError{}
