// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: companion.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConversationMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConversationMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationMessageMultiError, or nil if none found.
func (m *ConversationMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageId

	// no validation rules for Role

	// no validation rules for Content

	// no validation rules for CreatedAt

	for idx, item := range m.GetAssets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConversationMessageValidationError{
						field:  fmt.Sprintf("Assets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConversationMessageValidationError{
						field:  fmt.Sprintf("Assets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConversationMessageValidationError{
					field:  fmt.Sprintf("Assets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ConversationMessageMultiError(errors)
	}

	return nil
}

// ConversationMessageMultiError is an error wrapping multiple validation
// errors returned by ConversationMessage.ValidateAll() if the designated
// constraints aren't met.
type ConversationMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationMessageMultiError) AllErrors() []error { return m }

// ConversationMessageValidationError is the validation error returned by
// ConversationMessage.Validate if the designated constraints aren't met.
type ConversationMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationMessageValidationError) ErrorName() string {
	return "ConversationMessageValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationMessageValidationError{}

// Validate checks the field values on MessageAsset with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageAsset) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageAsset with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageAssetMultiError, or
// nil if none found.
func (m *MessageAsset) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageAsset) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageAssetId

	// no validation rules for AssetId

	// no validation rules for MediaType

	// no validation rules for ContentType

	// no validation rules for Filename

	// no validation rules for Url

	// no validation rules for SizeBytes

	if len(errors) > 0 {
		return MessageAssetMultiError(errors)
	}

	return nil
}

// MessageAssetMultiError is an error wrapping multiple validation errors
// returned by MessageAsset.ValidateAll() if the designated constraints aren't met.
type MessageAssetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageAssetMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageAssetMultiError) AllErrors() []error { return m }

// MessageAssetValidationError is the validation error returned by
// MessageAsset.Validate if the designated constraints aren't met.
type MessageAssetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageAssetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageAssetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageAssetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageAssetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageAssetValidationError) ErrorName() string { return "MessageAssetValidationError" }

// Error satisfies the builtin error interface
func (e MessageAssetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageAsset.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageAssetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageAssetValidationError{}

// Validate checks the field values on GetTimelineRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTimelineRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTimelineRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTimelineRequestMultiError, or nil if none found.
func (m *GetTimelineRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTimelineRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetTimelineRequestMultiError(errors)
	}

	return nil
}

// GetTimelineRequestMultiError is an error wrapping multiple validation errors
// returned by GetTimelineRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTimelineRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTimelineRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTimelineRequestMultiError) AllErrors() []error { return m }

// GetTimelineRequestValidationError is the validation error returned by
// GetTimelineRequest.Validate if the designated constraints aren't met.
type GetTimelineRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTimelineRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTimelineRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTimelineRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTimelineRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTimelineRequestValidationError) ErrorName() string {
	return "GetTimelineRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTimelineRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTimelineRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTimelineRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTimelineRequestValidationError{}

// Validate checks the field values on TimelineReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TimelineReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TimelineReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TimelineReplyMultiError, or
// nil if none found.
func (m *TimelineReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TimelineReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TimelineReplyValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TimelineReplyValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TimelineReplyValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TimelineReplyMultiError(errors)
	}

	return nil
}

// TimelineReplyMultiError is an error wrapping multiple validation errors
// returned by TimelineReply.ValidateAll() if the designated constraints
// aren't met.
type TimelineReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TimelineReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TimelineReplyMultiError) AllErrors() []error { return m }

// TimelineReplyValidationError is the validation error returned by
// TimelineReply.Validate if the designated constraints aren't met.
type TimelineReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TimelineReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TimelineReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TimelineReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TimelineReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TimelineReplyValidationError) ErrorName() string { return "TimelineReplyValidationError" }

// Error satisfies the builtin error interface
func (e TimelineReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTimelineReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TimelineReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TimelineReplyValidationError{}

// Validate checks the field values on SendMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageRequestMultiError, or nil if none found.
func (m *SendMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Content

	if len(errors) > 0 {
		return SendMessageRequestMultiError(errors)
	}

	return nil
}

// SendMessageRequestMultiError is an error wrapping multiple validation errors
// returned by SendMessageRequest.ValidateAll() if the designated constraints
// aren't met.
type SendMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageRequestMultiError) AllErrors() []error { return m }

// SendMessageRequestValidationError is the validation error returned by
// SendMessageRequest.Validate if the designated constraints aren't met.
type SendMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageRequestValidationError) ErrorName() string {
	return "SendMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageRequestValidationError{}

// Validate checks the field values on SendMessageReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageReplyMultiError, or nil if none found.
func (m *SendMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUserMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "UserMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "UserMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendMessageReplyValidationError{
				field:  "UserMessage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAssistantMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "AssistantMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendMessageReplyValidationError{
					field:  "AssistantMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAssistantMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendMessageReplyValidationError{
				field:  "AssistantMessage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SendMessageReplyMultiError(errors)
	}

	return nil
}

// SendMessageReplyMultiError is an error wrapping multiple validation errors
// returned by SendMessageReply.ValidateAll() if the designated constraints
// aren't met.
type SendMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageReplyMultiError) AllErrors() []error { return m }

// SendMessageReplyValidationError is the validation error returned by
// SendMessageReply.Validate if the designated constraints aren't met.
type SendMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageReplyValidationError) ErrorName() string { return "SendMessageReplyValidationError" }

// Error satisfies the builtin error interface
func (e SendMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageReplyValidationError{}

// Validate checks the field values on SendAudioMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendAudioMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendAudioMessageRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendAudioMessageRequestMultiError, or nil if none found.
func (m *SendAudioMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendAudioMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AudioData

	// no validation rules for Filename

	// no validation rules for ContentType

	// no validation rules for Language

	// no validation rules for Voice

	// no validation rules for Synthesize

	if len(errors) > 0 {
		return SendAudioMessageRequestMultiError(errors)
	}

	return nil
}

// SendAudioMessageRequestMultiError is an error wrapping multiple validation
// errors returned by SendAudioMessageRequest.ValidateAll() if the designated
// constraints aren't met.
type SendAudioMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendAudioMessageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendAudioMessageRequestMultiError) AllErrors() []error { return m }

// SendAudioMessageRequestValidationError is the validation error returned by
// SendAudioMessageRequest.Validate if the designated constraints aren't met.
type SendAudioMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendAudioMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendAudioMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendAudioMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendAudioMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendAudioMessageRequestValidationError) ErrorName() string {
	return "SendAudioMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendAudioMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendAudioMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendAudioMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendAudioMessageRequestValidationError{}

// Validate checks the field values on SendAudioMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendAudioMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendAudioMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendAudioMessageReplyMultiError, or nil if none found.
func (m *SendAudioMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendAudioMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendAudioMessageReplyValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendAudioMessageReplyValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendAudioMessageReplyValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AudioData

	// no validation rules for AudioContentType

	if len(errors) > 0 {
		return SendAudioMessageReplyMultiError(errors)
	}

	return nil
}

// SendAudioMessageReplyMultiError is an error wrapping multiple validation
// errors returned by SendAudioMessageReply.ValidateAll() if the designated
// constraints aren't met.
type SendAudioMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendAudioMessageReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendAudioMessageReplyMultiError) AllErrors() []error { return m }

// SendAudioMessageReplyValidationError is the validation error returned by
// SendAudioMessageReply.Validate if the designated constraints aren't met.
type SendAudioMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendAudioMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendAudioMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendAudioMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendAudioMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendAudioMessageReplyValidationError) ErrorName() string {
	return "SendAudioMessageReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SendAudioMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendAudioMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendAudioMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendAudioMessageReplyValidationError{}

// Validate checks the field values on SendMediaMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMediaMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMediaMessageRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMediaMessageRequestMultiError, or nil if none found.
func (m *SendMediaMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMediaMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	// no validation rules for Filename

	// no validation rules for ContentType

	// no validation rules for MediaType

	// no validation rules for Caption

	// no validation rules for Synthesize

	// no validation rules for Voice

	if len(errors) > 0 {
		return SendMediaMessageRequestMultiError(errors)
	}

	return nil
}

// SendMediaMessageRequestMultiError is an error wrapping multiple validation
// errors returned by SendMediaMessageRequest.ValidateAll() if the designated
// constraints aren't met.
type SendMediaMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMediaMessageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMediaMessageRequestMultiError) AllErrors() []error { return m }

// SendMediaMessageRequestValidationError is the validation error returned by
// SendMediaMessageRequest.Validate if the designated constraints aren't met.
type SendMediaMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMediaMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMediaMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMediaMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMediaMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMediaMessageRequestValidationError) ErrorName() string {
	return "SendMediaMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendMediaMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMediaMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMediaMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMediaMessageRequestValidationError{}

// Validate checks the field values on SendMediaMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMediaMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMediaMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMediaMessageReplyMultiError, or nil if none found.
func (m *SendMediaMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMediaMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendMediaMessageReplyValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendMediaMessageReplyValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendMediaMessageReplyValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SendMediaMessageReplyMultiError(errors)
	}

	return nil
}

// SendMediaMessageReplyMultiError is an error wrapping multiple validation
// errors returned by SendMediaMessageReply.ValidateAll() if the designated
// constraints aren't met.
type SendMediaMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMediaMessageReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMediaMessageReplyMultiError) AllErrors() []error { return m }

// SendMediaMessageReplyValidationError is the validation error returned by
// SendMediaMessageReply.Validate if the designated constraints aren't met.
type SendMediaMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMediaMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMediaMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMediaMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMediaMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMediaMessageReplyValidationError) ErrorName() string {
	return "SendMediaMessageReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SendMediaMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMediaMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMediaMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMediaMessageReplyValidationError{}

// Validate checks the field values on MessageChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageChunkMultiError, or
// nil if none found.
func (m *MessageChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageId

	// no validation rules for Delta

	// no validation rules for FinishReason

	// no validation rules for Done

	if len(errors) > 0 {
		return MessageChunkMultiError(errors)
	}

	return nil
}

// MessageChunkMultiError is an error wrapping multiple validation errors
// returned by MessageChunk.ValidateAll() if the designated constraints aren't met.
type MessageChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageChunkMultiError) AllErrors() []error { return m }

// MessageChunkValidationError is the validation error returned by
// MessageChunk.Validate if the designated constraints aren't met.
type MessageChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageChunkValidationError) ErrorName() string { return "MessageChunkValidationError" }

// Error satisfies the builtin error interface
func (e MessageChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageChunkValidationError{}

// Validate checks the field values on MemoryFeedbackRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MemoryFeedbackRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoryFeedbackRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MemoryFeedbackRequestMultiError, or nil if none found.
func (m *MemoryFeedbackRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoryFeedbackRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageId

	// no validation rules for Action

	// no validation rules for Kind

	// no validation rules for Content

	if len(errors) > 0 {
		return MemoryFeedbackRequestMultiError(errors)
	}

	return nil
}

// MemoryFeedbackRequestMultiError is an error wrapping multiple validation
// errors returned by MemoryFeedbackRequest.ValidateAll() if the designated
// constraints aren't met.
type MemoryFeedbackRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoryFeedbackRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoryFeedbackRequestMultiError) AllErrors() []error { return m }

// MemoryFeedbackRequestValidationError is the validation error returned by
// MemoryFeedbackRequest.Validate if the designated constraints aren't met.
type MemoryFeedbackRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoryFeedbackRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoryFeedbackRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoryFeedbackRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoryFeedbackRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoryFeedbackRequestValidationError) ErrorName() string {
	return "MemoryFeedbackRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MemoryFeedbackRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoryFeedbackRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoryFeedbackRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoryFeedbackRequestValidationError{}

// Validate checks the field values on MemoryFeedbackReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MemoryFeedbackReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoryFeedbackReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MemoryFeedbackReplyMultiError, or nil if none found.
func (m *MemoryFeedbackReply) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoryFeedbackReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Accepted

	if len(errors) > 0 {
		return MemoryFeedbackReplyMultiError(errors)
	}

	return nil
}

// MemoryFeedbackReplyMultiError is an error wrapping multiple validation
// errors returned by MemoryFeedbackReply.ValidateAll() if the designated
// constraints aren't met.
type MemoryFeedbackReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoryFeedbackReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoryFeedbackReplyMultiError) AllErrors() []error { return m }

// MemoryFeedbackReplyValidationError is the validation error returned by
// MemoryFeedbackReply.Validate if the designated constraints aren't met.
type MemoryFeedbackReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoryFeedbackReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoryFeedbackReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoryFeedbackReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoryFeedbackReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoryFeedbackReplyValidationError) ErrorName() string {
	return "MemoryFeedbackReplyValidationError"
}

// Error satisfies the builtin error interface
func (e MemoryFeedbackReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoryFeedbackReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoryFeedbackReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoryFeedbackReplyValidationError{}
