// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: companion.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanionId    string                 `protobuf:"bytes,3,opt,name=companion_id,json=companionId,proto3" json:"companion_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary        string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Messages       []*ConversationMessage `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_companion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Conversation) GetCompanionId() string {
	if x != nil {
		return x.CompanionId
	}
	return ""
}

func (x *Conversation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Conversation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Conversation) GetMessages() []*ConversationMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Conversation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Conversation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_companion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConversationMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanionId   string                 `protobuf:"bytes,1,opt,name=companion_id,json=companionId,proto3" json:"companion_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_companion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{2}
}

func (x *CreateConversationRequest) GetCompanionId() string {
	if x != nil {
		return x.CompanionId
	}
	return ""
}

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_companion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{3}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_companion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ConversationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationReply) Reset() {
	*x = ConversationReply{}
	mi := &file_companion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationReply) ProtoMessage() {}

func (x *ConversationReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationReply.ProtoReflect.Descriptor instead.
func (*ConversationReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationReply) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type SendMessageReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserMessage      *ConversationMessage   `protobuf:"bytes,1,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AssistantMessage *ConversationMessage   `protobuf:"bytes,2,opt,name=assistant_message,json=assistantMessage,proto3" json:"assistant_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_companion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_companion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_companion_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageReply) GetUserMessage() *ConversationMessage {
	if x != nil {
		return x.UserMessage
	}
	return nil
}

func (x *SendMessageReply) GetAssistantMessage() *ConversationMessage {
	if x != nil {
		return x.AssistantMessage
	}
	return nil
}

var File_companion_proto protoreflect.FileDescriptor

const file_companion_proto_rawDesc = "" +
	"\n" +
	"\x0fcompanion.proto\x12\fcompanion.v1\x1a\x1cgoogle/api/annotations.proto\"\xa2\x02\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fcompanion_id\x18\x03 \x01(\tR\vcompanionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12=\n" +
	"\bmessages\x18\x06 \x03(\v2!.companion.v1.ConversationMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x81\x01\n" +
	"\x13ConversationMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\">\n" +
	"\x19CreateConversationRequest\x12!\n" +
	"\fcompanion_id\x18\x01 \x01(\tR\vcompanionId\"A\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"W\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"S\n" +
	"\x11ConversationReply\x12>\n" +
	"\fconversation\x18\x01 \x01(\v2\x1a.companion.v1.ConversationR\fconversation\"\xa8\x01\n" +
	"\x10SendMessageReply\x12D\n" +
	"\fuser_message\x18\x01 \x01(\v2!.companion.v1.ConversationMessageR\vuserMessage\x12N\n" +
	"\x11assistant_message\x18\x02 \x01(\v2!.companion.v1.ConversationMessageR\x10assistantMessage2\xbb\x03\n" +
	"\tCompanion\x12\x86\x01\n" +
	"\x12CreateConversation\x12'.companion.v1.CreateConversationRequest\x1a\x1f.companion.v1.ConversationReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/companion/v1/conversations\x12\x8f\x01\n" +
	"\x0fGetConversation\x12$.companion.v1.GetConversationRequest\x1a\x1f.companion.v1.ConversationReply\"5\x82\xd3\xe4\x93\x02/\x12-/companion/v1/conversations/{conversation_id}\x12\x92\x01\n" +
	"\vSendMessage\x12 .companion.v1.SendMessageRequest\x1a\x1e.companion.v1.SendMessageReply\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/companion/v1/conversations/{conversation_id}/messagesB'Z%companion-service/api/companion/v1;v1b\x06proto3"

var (
	file_companion_proto_rawDescOnce sync.Once
	file_companion_proto_rawDescData []byte
)

func file_companion_proto_rawDescGZIP() []byte {
	file_companion_proto_rawDescOnce.Do(func() {
		file_companion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_companion_proto_rawDesc), len(file_companion_proto_rawDesc)))
	})
	return file_companion_proto_rawDescData
}

var file_companion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_companion_proto_goTypes = []any{
	(*Conversation)(nil),              // 0: companion.v1.Conversation
	(*ConversationMessage)(nil),       // 1: companion.v1.ConversationMessage
	(*CreateConversationRequest)(nil), // 2: companion.v1.CreateConversationRequest
	(*GetConversationRequest)(nil),    // 3: companion.v1.GetConversationRequest
	(*SendMessageRequest)(nil),        // 4: companion.v1.SendMessageRequest
	(*ConversationReply)(nil),         // 5: companion.v1.ConversationReply
	(*SendMessageReply)(nil),          // 6: companion.v1.SendMessageReply
}
var file_companion_proto_depIdxs = []int32{
	1, // 0: companion.v1.Conversation.messages:type_name -> companion.v1.ConversationMessage
	0, // 1: companion.v1.ConversationReply.conversation:type_name -> companion.v1.Conversation
	1, // 2: companion.v1.SendMessageReply.user_message:type_name -> companion.v1.ConversationMessage
	1, // 3: companion.v1.SendMessageReply.assistant_message:type_name -> companion.v1.ConversationMessage
	2, // 4: companion.v1.Companion.CreateConversation:input_type -> companion.v1.CreateConversationRequest
	3, // 5: companion.v1.Companion.GetConversation:input_type -> companion.v1.GetConversationRequest
	4, // 6: companion.v1.Companion.SendMessage:input_type -> companion.v1.SendMessageRequest
	5, // 7: companion.v1.Companion.CreateConversation:output_type -> companion.v1.ConversationReply
	5, // 8: companion.v1.Companion.GetConversation:output_type -> companion.v1.ConversationReply
	6, // 9: companion.v1.Companion.SendMessage:output_type -> companion.v1.SendMessageReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_companion_proto_init() }
func file_companion_proto_init() {
	if File_companion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_companion_proto_rawDesc), len(file_companion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_companion_proto_goTypes,
		DependencyIndexes: file_companion_proto_depIdxs,
		MessageInfos:      file_companion_proto_msgTypes,
	}.Build()
	File_companion_proto = out.File
	file_companion_proto_goTypes = nil
	file_companion_proto_depIdxs = nil
}
