// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: companion.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCompanionGetTimeline = "/companion.v1.Companion/GetTimeline"
const OperationCompanionSendAudioMessage = "/companion.v1.Companion/SendAudioMessage"
const OperationCompanionSendMessage = "/companion.v1.Companion/SendMessage"
const OperationCompanionSubmitMemoryFeedback = "/companion.v1.Companion/SubmitMemoryFeedback"

type CompanionHTTPServer interface {
	GetTimeline(context.Context, *GetTimelineRequest) (*TimelineReply, error)
	SendAudioMessage(context.Context, *SendAudioMessageRequest) (*SendAudioMessageReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	SubmitMemoryFeedback(context.Context, *MemoryFeedbackRequest) (*MemoryFeedbackReply, error)
}

func RegisterCompanionHTTPServer(s *http.Server, srv CompanionHTTPServer) {
	r := s.Route("/")
	r.GET("/companion/v1/timeline", _Companion_GetTimeline0_HTTP_Handler(srv))
	r.POST("/companion/v1/messages", _Companion_SendMessage0_HTTP_Handler(srv))
	r.POST("/companion/v1/audio-messages", _Companion_SendAudioMessage0_HTTP_Handler(srv))
	r.POST("/companion/v1/memory-feedback", _Companion_SubmitMemoryFeedback0_HTTP_Handler(srv))
}

func _Companion_GetTimeline0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTimelineRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetTimeline)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTimeline(ctx, req.(*GetTimelineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TimelineReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SendMessage0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SendAudioMessage0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendAudioMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSendAudioMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendAudioMessage(ctx, req.(*SendAudioMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendAudioMessageReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SubmitMemoryFeedback0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MemoryFeedbackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSubmitMemoryFeedback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitMemoryFeedback(ctx, req.(*MemoryFeedbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemoryFeedbackReply)
		return ctx.Result(200, reply)
	}
}

type CompanionHTTPClient interface {
	GetTimeline(ctx context.Context, req *GetTimelineRequest, opts ...http.CallOption) (rsp *TimelineReply, err error)
	SendAudioMessage(ctx context.Context, req *SendAudioMessageRequest, opts ...http.CallOption) (rsp *SendAudioMessageReply, err error)
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
	SubmitMemoryFeedback(ctx context.Context, req *MemoryFeedbackRequest, opts ...http.CallOption) (rsp *MemoryFeedbackReply, err error)
}

type CompanionHTTPClientImpl struct {
	cc *http.Client
}

func NewCompanionHTTPClient(client *http.Client) CompanionHTTPClient {
	return &CompanionHTTPClientImpl{client}
}

func (c *CompanionHTTPClientImpl) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...http.CallOption) (*TimelineReply, error) {
	var out TimelineReply
	pattern := "/companion/v1/timeline"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetTimeline))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SendAudioMessage(ctx context.Context, in *SendAudioMessageRequest, opts ...http.CallOption) (*SendAudioMessageReply, error) {
	var out SendAudioMessageReply
	pattern := "/companion/v1/audio-messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSendAudioMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/companion/v1/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SubmitMemoryFeedback(ctx context.Context, in *MemoryFeedbackRequest, opts ...http.CallOption) (*MemoryFeedbackReply, error) {
	var out MemoryFeedbackReply
	pattern := "/companion/v1/memory-feedback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSubmitMemoryFeedback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
