// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: companion.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCompanionCreateConversation = "/companion.v1.Companion/CreateConversation"
const OperationCompanionGetConversation = "/companion.v1.Companion/GetConversation"
const OperationCompanionSendMessage = "/companion.v1.Companion/SendMessage"

type CompanionHTTPServer interface {
	CreateConversation(context.Context, *CreateConversationRequest) (*ConversationReply, error)
	GetConversation(context.Context, *GetConversationRequest) (*ConversationReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
}

func RegisterCompanionHTTPServer(s *http.Server, srv CompanionHTTPServer) {
	r := s.Route("/")
	r.POST("/companion/v1/conversations", _Companion_CreateConversation0_HTTP_Handler(srv))
	r.GET("/companion/v1/conversations/{conversation_id}", _Companion_GetConversation0_HTTP_Handler(srv))
	r.POST("/companion/v1/conversations/{conversation_id}/messages", _Companion_SendMessage0_HTTP_Handler(srv))
}

func _Companion_CreateConversation0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConversationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionCreateConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConversation(ctx, req.(*CreateConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetConversation0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConversationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConversation(ctx, req.(*GetConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SendMessage0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

type CompanionHTTPClient interface {
	CreateConversation(ctx context.Context, req *CreateConversationRequest, opts ...http.CallOption) (rsp *ConversationReply, err error)
	GetConversation(ctx context.Context, req *GetConversationRequest, opts ...http.CallOption) (rsp *ConversationReply, err error)
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
}

type CompanionHTTPClientImpl struct {
	cc *http.Client
}

func NewCompanionHTTPClient(client *http.Client) CompanionHTTPClient {
	return &CompanionHTTPClientImpl{client}
}

func (c *CompanionHTTPClientImpl) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...http.CallOption) (*ConversationReply, error) {
	var out ConversationReply
	pattern := "/companion/v1/conversations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionCreateConversation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...http.CallOption) (*ConversationReply, error) {
	var out ConversationReply
	pattern := "/companion/v1/conversations/{conversation_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetConversation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/companion/v1/conversations/{conversation_id}/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
