// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"companion-service/internal/biz"
	"companion-service/internal/client"
	"companion-service/internal/conf"
	"companion-service/internal/data"
	"companion-service/internal/memory"
	"companion-service/internal/server"
	"companion-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	http := conf.NewHTTPConfig(bootstrap)
	confData := conf.NewDataConfig(bootstrap)
	store, cleanup, err := data.NewStore(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	modelGateway := conf.NewModelGatewayConfig(bootstrap)
	modelGatewayClient, cleanup2, err := client.NewModelGatewayClient(modelGateway)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	confMemory := conf.NewMemoryConfig(bootstrap)
	processor, cleanup3 := memory.NewProcessor(confMemory, store, modelGatewayClient, logger)
	companionUsecase := biz.NewCompanionUsecase(store, modelGatewayClient, processor)
	companionService := service.NewCompanionService(companionUsecase)
	httpServer := server.NewHTTPServer(http, companionService)
	grpc := conf.NewGRPCConfig(bootstrap)
	grpcServer := server.NewGRPCServer(grpc, companionService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
